body:
  - type: markdown
    attributes:
      value: |
        ### ❤ Information
        We have to inform you that we are doing this extracurricularly, so you may not receive help instantly.
        However, we will reply as soon as possible. Thanks for your understanding!
  - type: textarea
    attributes:
      label: Details of the problem
      description: |
        Introduce the problem clearly. Be specific and imagine you're asking a question to another person.
        Insert screenshots or recorded videos if neccessary. You may also paste compile errors or console errors you've encountered (if there is any). Make sure to copy the entire error.
        If you are willing to use a paste site, please use something like https://gist.github.com or https://pastebin.com.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What you have done
      description: |
        Describe what you tried, what you expected to happen, and what actually resulted.
        Insert screenshots or recorded videos if neccessary. You may also paste compile errors or console errors you've encountered (if there is any). Make sure to copy the entire error.
        If you are willing to use a paste site, please use something like https://gist.github.com or https://pastebin.com.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Have anything else to add?
        Let us know if you have any additional feedback!
    validations:
      required: false
      